Add file_metadata and improve upload_file
uploadcare/uploadcare-ruby pull request #100
Opened 2022-09-21 08:11 UTC by T0mbery

## Description

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-09-28 10:16 UTC, dmitrijivanchenko requested changes

2022-09-28 10:16 UTC, dmitrijivanchenko commented on lib/uploadcare/entity/file_metadata.rb
> +          '200 OK' if ::Uploadcare::Client::FileMetadataClient.new.delete(uuid, key).success?
думаю, что тут лучше вертать ответ сервера, не строку. Так как он может измениться и в будущем нужен конечному юзеру

```suggestion
          ::Uploadcare::Client::FileMetadataClient.new.delete(uuid, key).success
```

2022-09-28 10:16 UTC, dmitrijivanchenko commented on lib/uploadcare/entity/file_metadata.rb
> +          ::Uploadcare::Client::FileMetadataClient.new.index(uuid).success
а если запрос не success, то что получит юзер?

2022-09-28 10:16 UTC, dmitrijivanchenko commented on lib/uploadcare/param/upload/upload_params_generator.rb
> +            }.merge(metadata(options)).reject { |_k, v| v.nil? }
такое подойдет тут?

```suggestion
            }.merge(metadata(options)).compact
```

2022-09-28 10:16 UTC, dmitrijivanchenko commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +        it "shows file's metadata keys and values" do
где-то file's, а где-то file. Давай сделаем одинаково. и кавычки. Советую гонять рубокопа

2022-09-28 10:16 UTC, dmitrijivanchenko commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +            expect(response.value![:subsystem]).to eq('test')
там одна пара ключ-значение?
другие не надо проверить?

2022-09-28 10:16 UTC, dmitrijivanchenko commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +        it 'update file metadata value by key' do
```suggestion
        it 'updates file metadata value by key' do
```

2022-09-28 10:16 UTC, dmitrijivanchenko commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +        it "delete a file's metadata key" do
кавычки

2022-09-28 10:16 UTC, dmitrijivanchenko commented on spec/uploadcare/entity/file_metadata_spec.rb
> +      it 'show file_metadata' do
```suggestion
      it 'shows file_metadata' do
```

2022-09-28 10:16 UTC, dmitrijivanchenko commented on spec/uploadcare/entity/file_metadata_spec.rb
> +      it 'update file_metadata' do
```suggestion
      it 'updates file_metadata' do
```

2022-09-28 10:16 UTC, dmitrijivanchenko commented on spec/uploadcare/entity/file_metadata_spec.rb
> +      it 'create file_metadata if it does not exist' do
```suggestion
      it 'creates file_metadata if it does not exist' do
```

2022-09-28 10:16 UTC, dmitrijivanchenko commented on spec/uploadcare/entity/file_metadata_spec.rb
> +      it 'delete file_metadata' do
```suggestion
      it 'deletes file_metadata' do
```

2022-09-29 11:59 UTC, T0mbery commented on lib/uploadcare/entity/file_metadata.rb
> +          ::Uploadcare::Client::FileMetadataClient.new.index(uuid).success
на все ответы о статусом >= 300 рейзится эксепшены (ErrorHandler#wrap), который потом перехватываются и формируются в обычную ошибку. То есть если будет не success, то до сюда даже дело не дойдёт.

2022-09-29 11:59 UTC, T0mbery commented on lib/uploadcare/param/upload/upload_params_generator.rb
> +            }.merge(metadata(options)).reject { |_k, v| v.nil? }
aga

2022-09-29 11:59 UTC, T0mbery commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +            expect(response.value![:subsystem]).to eq('test')
тут только одна, т.к. это запрос за значением метадаты по конкретному (единственному) ключу.

2022-09-29 13:18 UTC, T0mbery commented on lib/uploadcare/entity/file_metadata.rb
> +          '200 OK' if ::Uploadcare::Client::FileMetadataClient.new.delete(uuid, key).success?
там просто `nil` возвращается, поэтому я решил лучше уж какую-то понятную инфу возвращать.

2022-09-29 13:25 UTC, T0mbery commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +        it "shows file's metadata keys and values" do
так рубоком на ci гоняется

2022-09-30 03:51 UTC, dmitrijivanchenko commented on lib/uploadcare/entity/file_metadata.rb
> +          '200 OK' if ::Uploadcare::Client::FileMetadataClient.new.delete(uuid, key).success?
давай тогда уж сделаем так:

```ruby
::Uploadcare::Client::FileMetadataClient.new.delete(uuid, key).success || '200 OK'
```
чтобы юзер хотя бы мог получить тело ответа, если оно есть

2022-09-30 03:54 UTC, dmitrijivanchenko commented on lib/uploadcare/entity/file_metadata.rb
> +          '200 OK' if ::Uploadcare::Client::FileMetadataClient.new.delete(uuid, key).success?
```suggestion
          ::Uploadcare::Client::FileMetadataClient.new.delete(uuid, key).success || '200 OK'
```

2022-09-30 03:54 UTC, dmitrijivanchenko commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +        it 'delete a file metadata key' do
```suggestion
        it 'deletes a file metadata key' do
```

2022-09-30 03:54 UTC, dmitrijivanchenko commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +        it "shows file's metadata keys and values" do
мож версия старая у него, странно

2022-09-30 03:58 UTC, dmitrijivanchenko requested changes

2022-09-30 03:58 UTC, dmitrijivanchenko commented on spec/uploadcare/client/file_metadata_client_spec.rb
> +        it 'update file metadata value by key' do
это надо поправить

2022-10-04 09:03 UTC, dmitrijivanchenko approved these changes

2022-10-07 20:27 UTC, merged