add delete method for group
uploadcare/uploadcare-ruby pull request #101
Opened 2022-09-21 16:54 UTC by T0mbery

## Description

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-09-28 10:19 UTC, dmitrijivanchenko requested changes

2022-09-28 10:19 UTC, dmitrijivanchenko commented on lib/uploadcare/entity/group.rb
> +        '200 OK' if rest_delete(uuid).success?
то же самое про возврат строки. Думаю, лучше вертать ответ, как есть от апи

2022-09-28 10:19 UTC, dmitrijivanchenko commented on spec/uploadcare/client/rest_group_client_spec.rb
> +        it "delete a file's group" do
```suggestion
        it 'deletes a file's group' do
```

2022-09-28 10:19 UTC, dmitrijivanchenko commented on spec/uploadcare/entity/group_spec.rb
> +        it "delete a file's group" do
```suggestion
        it 'deletes a file's group' do
```

2022-09-29 13:40 UTC, T0mbery commented on lib/uploadcare/entity/group.rb
> +        '200 OK' if rest_delete(uuid).success?
'200 OK' лучше чем nil

2022-10-04 09:03 UTC, dmitrijivanchenko approved these changes

2022-10-07 20:20 UTC, merged