remove store method for rest_group
uploadcare/uploadcare-ruby pull request #102
Opened 2022-09-21 17:18 UTC by T0mbery

## Description

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-09-28 10:22 UTC, dmitrijivanchenko commented
Тут надо обязательно пометить в ридми или changelog c восклицательными знаками, что после вкатывания этого ПР в рельсовой либе сломается store-ing групп.

2022-09-30 04:08 UTC, dmitrijivanchenko approved these changes

2022-09-30 10:48 UTC, dmitrijivanchenko requested changes

2022-09-30 10:48 UTC, dmitrijivanchenko commented on spec/uploadcare/client/rest_group_client_spec.rb
> +        it 'get a file group by its ID.' do
```suggestion
        it 'gets a file group by its ID.' do
```

2022-09-30 10:48 UTC, dmitrijivanchenko commented on lib/uploadcare/client/rest_group_client.rb
> +        files.each_slice(100) do |file_chunk|
тут 100 лучше вынести в параметр с дефолтом, так как юзеры могут захотеть настраивать это

2022-09-30 10:48 UTC, dmitrijivanchenko commented on lib/uploadcare/client/rest_group_client.rb
> -      # @see https://uploadcare.com/api-refs/rest-api/v0.5.0/#tag/Group/paths/~1groups~1%3Cuuid%3E~1storage~1/put
сюда можно приложить ссыль на метод для сторинга файла

2022-09-30 10:48 UTC, dmitrijivanchenko commented on lib/uploadcare/client/rest_group_client.rb
> +            ::Uploadcare::Client::FileClient.new.store(file[:uuid])
давай вынесем создание обеъкта из цикла, так как нет смысла создавать объект в каждой итерации

2022-09-30 10:51 UTC, T0mbery commented on lib/uploadcare/client/rest_group_client.rb
> -      # @see https://uploadcare.com/api-refs/rest-api/v0.5.0/#tag/Group/paths/~1groups~1%3Cuuid%3E~1storage~1/put
не понял. какую ссылку? её же больше нет в АПИ

2022-09-30 10:51 UTC, T0mbery commented on lib/uploadcare/client/rest_group_client.rb
> +        files.each_slice(100) do |file_chunk|
ок

2022-09-30 10:51 UTC, T0mbery commented on lib/uploadcare/client/rest_group_client.rb
> +            ::Uploadcare::Client::FileClient.new.store(file[:uuid])
не пойму что ты имеешь ввиду

2022-09-30 10:52 UTC, dmitrijivanchenko commented on lib/uploadcare/client/rest_group_client.rb
> -      # @see https://uploadcare.com/api-refs/rest-api/v0.5.0/#tag/Group/paths/~1groups~1%3Cuuid%3E~1storage~1/put
https://uploadcare.com/api-refs/rest-api/v0.7.0/#operation/deleteFileStorage

2022-09-30 10:54 UTC, T0mbery commented on lib/uploadcare/client/rest_group_client.rb
> -      # @see https://uploadcare.com/api-refs/rest-api/v0.5.0/#tag/Group/paths/~1groups~1%3Cuuid%3E~1storage~1/put
а причём тут удаление?
тут же речь про storage

2022-09-30 10:55 UTC, dmitrijivanchenko commented on lib/uploadcare/client/rest_group_client.rb
> +            ::Uploadcare::Client::FileClient.new.store(file[:uuid])
Сейчас `.new` вызывается в цикле, а значит мы создаем объект клиента для каждого файла новый.
Если вынесем это из цикла, то получится создавать всего 1 объект клиента на все файлы - меньше памяти расходуется

```ruby
      def store(uuid)
        files = info(uuid).success[:files]
        client = ::Uploadcare::Client::FileClient.new
        files.each_slice(100) do |file_chunk|
          file_chunk.each do |file|
            client.store(file[:uuid])
          end
        end

        Dry::Monads::Success(true)
      end
```

2022-09-30 10:55 UTC, dmitrijivanchenko commented on lib/uploadcare/client/rest_group_client.rb
> -      # @see https://uploadcare.com/api-refs/rest-api/v0.5.0/#tag/Group/paths/~1groups~1%3Cuuid%3E~1storage~1/put
а, точно, я попутал. Вот эта ссыль - https://uploadcare.com/api-refs/rest-api/v0.7.0/#operation/storeFile

2022-09-30 10:56 UTC, T0mbery commented on lib/uploadcare/client/rest_group_client.rb
> -      # @see https://uploadcare.com/api-refs/rest-api/v0.5.0/#tag/Group/paths/~1groups~1%3Cuuid%3E~1storage~1/put
понял, ты об этом наверно - https://uploadcare.com/api-refs/rest-api/v0.7.0/#operation/storeFile

2022-09-30 10:57 UTC, dmitrijivanchenko commented on lib/uploadcare/client/rest_group_client.rb
> -      # @see https://uploadcare.com/api-refs/rest-api/v0.5.0/#tag/Group/paths/~1groups~1%3Cuuid%3E~1storage~1/put
ну или это, выглядит одинаково)

2022-09-30 11:05 UTC, T0mbery commented on lib/uploadcare/client/rest_group_client.rb
> +            ::Uploadcare::Client::FileClient.new.store(file[:uuid])
согласен

2022-09-30 12:22 UTC, dmitrijivanchenko approved these changes

2022-10-07 20:07 UTC, merged