add addons section
uploadcare/uploadcare-ruby pull request #105
Opened 2022-09-23 12:16 UTC by T0mbery

## Description

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-09-28 10:36 UTC, dmitrijivanchenko requested changes

2022-09-28 10:36 UTC, dmitrijivanchenko commented on README.md
> +# Remove background image removal Add-On for a given target.
Мне кажется или тут предложение не осгласовано. Может так лучше:

```suggestion
# Background image removal Add-On for a given target.
```

2022-09-28 10:36 UTC, dmitrijivanchenko commented on README.md
> +# Check the status background image removal.
```suggestion
# Check the status of background image removal.
```

2022-09-28 10:36 UTC, dmitrijivanchenko commented on README.md
> +Uploadcare::Addons.remove_bg('RETURNED_ID_FROM_REMOVE_BG')
думаю, тут так должно быть

```suggestion
Uploadcare::Addons.remove_bg_status('RETURNED_ID_FROM_REMOVE_BG')
```

2022-09-28 10:36 UTC, dmitrijivanchenko commented on lib/uploadcare/client/addons_client.rb
> +      # @see https://uploadcare.com/api-refs/rest-api/v0.7.0/#operation/awsRekognitionExecute
ссылка не та вроде

2022-09-28 10:36 UTC, dmitrijivanchenko commented on spec/uploadcare/client/addons_client_spec.rb
> +        it 'execute aws rekognition' do
здесь и ниже есть такое же

```suggestion
        it 'executes aws rekognition' do
```

2022-09-28 10:36 UTC, dmitrijivanchenko commented on spec/uploadcare/entity/addons.rb
> +        it 'scan the file for viruses' do
здесь и ниже

```suggestion
        it 'scans the file for viruses' do
```

2022-10-03 18:46 UTC, rsedykh requested changes

2022-10-03 18:46 UTC, rsedykh commented on README.md
> +#### Add-Ons
Can you add description for every add-on (you can copy them from the api-refs)?

2022-10-04 09:09 UTC, dmitrijivanchenko requested changes

2022-10-04 09:09 UTC, dmitrijivanchenko commented on spec/uploadcare/client/addons_client_spec.rb
> +        it 'scan the file for viruses' do
тут кажется осталось неправлено

2022-10-06 13:32 UTC, rsedykh commented on README.md
> +#### Add-Ons
Just a human-plain-english description. Not everybody goes to the api-refs or even docs to check it out. Usually people just read readme, and that's it for them. If they don't get it from here, they won't get it anywhere else. :-(

2022-10-07 13:21 UTC, merged