ID-1: Edit readme. Fix webhook create args
uploadcare/uploadcare-ruby pull request #77
Opened 2021-08-02 07:40 UTC by dmitrijivanchenko

## Description

### [Documents conversion](https://uploadcare-evrone.atlassian.net/browse/UC-1)

- Add docs for:
  - copy File
  - list/update/delete Webhook
  - store Group
- Fix webhooks create method args

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2021-08-02 13:45 UTC, rsedykh requested changes

2021-08-02 13:45 UTC, rsedykh commented on README.md
> +@file.store # copies file, returns a new (copied) file metadata
`@file.copy`?

2021-08-06 09:57 UTC, dmitrijivanchenko commented on README.md
> +@file.store # copies file, returns a new (copied) file metadata
:+1:

2021-08-10 14:55 UTC, rsedykh approved these changes

2021-08-18 14:18 UTC, dmitry-mukhin approved these changes

2021-08-22 13:12 UTC, evgeniy-r commented on lib/uploadcare/client/webhook_client.rb
> +          'is_active': options[:is_active] || true
It seems that we get `"is_active": true` if we send `is_active: false`. Is this OK?

2021-08-22 13:15 UTC, evgeniy-r commented on lib/uploadcare/client/webhook_client.rb
> +          'is_active': options[:is_active] || true
Maybe use
```ruby
'is_active': options[:is_active].nil? ? true : options[:is_active]
```

2021-08-22 13:16 UTC, evgeniy-r commented on lib/uploadcare/client/webhook_client.rb
> +          'is_active': options[:is_active] || true
And possibly we should add a test for this case.

2021-09-01 14:54 UTC, evgeniy-r approved these changes

2021-09-03 03:06 UTC, merged