Add options for secure webhooks
uploadcare/uploadcare-ruby pull request #91
Opened 2021-11-16 06:02 UTC by dmitrijivanchenko

## Description

- Add option "signing secret" for #create and #update webhooks methods

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2021-11-16 11:42 UTC, dmitry-mukhin requested changes
I think, we can add an example of signature validation function to the docs.
Ideally, it may be a helper/utility function of the lib (not API) next to generating other signatures. What do you think?

2021-11-16 16:25 UTC, rsedykh approved these changes

2021-11-18 05:57 UTC, dmitrijivanchenko commented on lib/uploadcare/client/project_client.rb
> +
Don't know, but tests start failing because of this. Actually, it is good practice to require classes that are used in the file.

2021-11-18 05:58 UTC, dmitrijivanchenko commented
> I think, we can add an example of signature validation function to the docs. Ideally, it may be a helper/utility function of the lib (not API) next to generating other signatures. What do you think?

Yeah, good idea, I'll add one

2021-11-18 13:59 UTC, rsedykh commented on README.md
> +webhook_body = "{\"payload_hash\":\"1844671900\",\"data\":{\"uuid\":\"f08d7c8a-2971-42e0-ab01-780d9039b40b\",\"image_info\":{\"color_mode\":\"RGB\",\"format\":\"JPEG\",\"height\":168,\"width\":300,\"
Can we make this (and the next) example better readable?

2021-11-22 10:40 UTC, dmitry-mukhin approved these changes
fix documentation example and ship

2021-11-22 10:40 UTC, dmitry-mukhin commented on README.md
> +webhook_body_json = '{"payload_hash":"13536412","data":{"uuid":"fe197bf1-9efa-4910-bbb7-5e3ec2637f6c","image_info":{"color_mode":"RGB","format":"JPEG","height":1200,"width":1600,"orientation":1,"dpi"
```suggestion
webhook_body_json = '{...}'
```

webhook body is not relevant to the example, but makes it much less readable. Just placeholder will be enough.

2021-11-25 06:11 UTC, merged